### ISSUE TITLE
" \ " not allowed in the "ProducerKeyFilePassphrase":

### ISSUE THREAD

**Issue by 0x3639** [HyperCore-Team/orchestrator#2]
If the `"ProducerKeyFilePassphrase": "test\" has a back slash in it we get the following error:

`Config malformed: please checkerrorinvalid character '_' in string escape code`

You need to manually escape the character within the quotes. I recommend we change the way this is parsed to avoid this error.

**Comment by 0x3639** [comment]
Another community member reported this is not an issue.  I have not confirmed the issue myself.

**Comment by 0x3639** [comment]
Another community member confirmed this issue.

![photo_2023-05-31_16-41-52](https://github.com/HyperCore-Team/orchestrator/assets/5406130/fdd54837-5329-41f2-b923-bacb0f65e005)

**Comment by 0x3639** [comment]
he actually had `\;` and was able to escape it with `\\;`

**Comment by mehowz** [comment]
For those who escape the invalid character, we'll need to be mindful to update producer passwords if this issue gets resolved.

**Comment by mehowz** [comment]
Also had an instance where the producer key password had `\"` characters in it.

Had to make it: `\\\"`
